const courses = [
  {
    id: "1",
    image: "https://www.simplilearn.com/ice9/free_resources_article_thumb/is_web_development_good_career.jpg",
    title: "Web Development",
    description: "Learn the basics of web development, including HTML, CSS, and JavaScript to build dynamic websites.",
    course1: "HTML",
    course2: "CSS",
    course3: "JavaScript",
    price: 5000,
  },
  {
    id: "2",
    image: "https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F3k3bha5ev11g2zyzca1w.jpg",
    title: "React Development",
    description: "Dive into the React framework and learn how to build efficient and interactive user interfaces.",
    course1: "React Basics",
    course2: "React Hooks",
    course3: "Redux",
    price: 7000,
  },
  {
    id: "3",
    image: "https://images.ctfassets.net/aq13lwl6616q/7cS8gBoWulxkWNWEm0FspJ/c7eb42dd82e27279307f8b9fc9b136fa/nodejs_cover_photo_smaller_size.png",
    title: "Node.js Development",
    description: "Master backend development with Node.js and create robust server-side applications.",
    course1: "Node.js",
    course2: "Express.js",
    course3: "MongoDB",
    price: 6000,
  },
  {
    id: "4",
    image: "https://media.licdn.com/dms/image/D5612AQHTGcgR9_RlDg/article-cover_image-shrink_600_2000/0/1705826273539?e=2147483647&v=beta&t=hZkuaC9fOago3ij77UdR45nXktn2C_R9nIwYiEGxVpU",
    title: "Python Programming",
    description: "Learn Python from scratch and explore its applications in web development, data science, and automation.",
    course1: "Python Basics",
    course2: "Flask",
    course3: "Django",
    price: 5500,
  },
  {
    id: "5",
    image: "https://www.simplilearn.com/ice9/free_resources_article_thumb/what_is_Data_Science.jpg",
    title: "Data Science",
    description: "Get introduced to data science concepts and tools, including data analysis, visualization, and machine learning.",
    course1: "Python for Data Science",
    course2: "Pandas",
    course3: "Scikit-Learn",
    price: 8000,
  },
  {
    id: "6",
    image: "https://d3an9kf42ylj3p.cloudfront.net/uploads/2023/05/pg_machinelearning101_may23.jpg",
    title: "Machine Learning",
    description: "Understand the fundamentals of machine learning and implement various algorithms using Python.",
    course1: "Machine Learning Basics",
    course2: "TensorFlow",
    course3: "Keras",
    price: 9000,
  },
  {
    id: "7",
    image: "https://www.cgtechnologies.com/wp-content/uploads/2023/01/what-is-cyber-security.jpg",
    title: "Cyber Security",
    description: "Learn how to protect systems and networks from cyber threats and attacks.",
    course1: "Network Security",
    course2: "Ethical Hacking",
    course3: "Cryptography",
    price: 7500,
  },
  {
    id: "8",
    image: "https://api.reliasoftware.com/uploads/the_complete_guide_to_mobile_app_development_2021_ded2abd1b1.png",
    title: "Mobile App Development",
    description: "Develop mobile applications for Android and iOS using React Native.",
    course1: "React Native Basics",
    course2: "Android Development",
    course3: "iOS Development",
    price: 8500,
  },
  {
    id: "9",
    image: "https://media.licdn.com/dms/image/D5612AQFwV7zzF8PreQ/article-cover_image-shrink_720_1280/0/1691465286767?e=2147483647&v=beta&t=glX0RA_O8iJ1zU1rwTikBf_oGzV9csXunhc-PwZbPnU",
    title: "UI/UX Design",
    description: "Learn the principles of user interface and user experience design to create visually appealing and user-friendly applications.",
    course1: "UI Design",
    course2: "UX Research",
    course3: "Prototyping",
    price: 5000,
  },
  {
    id: "10",
    image: "https://i.pcmag.com/imagery/articles/01nZo4Ot4FUIqaAccrCZGN9-9..v1569490627.jpg",
    title: "Cloud Computing",
    description: "Understand cloud computing concepts and learn how to deploy and manage applications on cloud platforms.",
    course1: "AWS Basics",
    course2: "Azure",
    course3: "Google Cloud",
    price: 9500,
  },
];

module.exports = courses;
